name: Metrics
on:
  # Roda a cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente se quiser testar na hora
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # --- Configuração Visual ---
          user: augusto-projetos
          template: classic
          base: header, activity
          config_timezone: America/Sao_Paulo
          config_theme: dracula
          
          # --- Linguagens ---
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          
          # --- Calendário 3D ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
