name: Metrics
on:
  # Roda a cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente se quiser testar na hora
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Opções gerais
          user: augusto-projetos
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          config_theme: dracula
          
          # PLUGIN: Linguagens (Substitui o "Top Langs")
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8
          
          # PLUGIN: Conquistas (Substitui o "Trophies")
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          # PLUGIN: Hábitos (Substitui o "Streak")
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_days: 14
          plugin_habits_from: 200
